### ISSUE TITLE
[charts/onechart] add hostNetwork

### ISSUE THREAD

**Issue by jpenschuck** [gimlet-io/onechart#111]
Would it be possible to add the spec.hostNetwork parameter for pods?
This i very helpful for pod whuch need access to the nodes networks.

Thanks!

**Comment by laszlocph** [comment]
This is certainly possible.

Please allow us to experiment with a new approach though: https://github.com/gimlet-io/onechart/issues/112
Recently we got a few feature requests, and perhaps an approach like this could solve most customization needs.

Either way: OneChart should get this feature before Christmas.
