### ISSUE TITLE
Additional Annotation for Services

### ISSUE THREAD

**Issue by joshuagibeonm** [gimlet-io/onechart#131]
We have a use case where we need to add additional annotation to services, such as GKE backend service annotation.
Some of custom annotation that we need to add:

- `cloud.google.com/backend-config`
- `cloud.google.com/neg`

I'm open to create PR to add this feature.

**Comment by laszlocph** [comment]
This would be a good addition thanks.

Could follow how the `podAnnotations` field is done.
