### ISSUE TITLE
Feature: Create Service Account

### ISSUE THREAD

**Issue by FacundoAcevedo** [gimlet-io/onechart#132]
I think it would be useful to also have the possibility to create and run the deployments under a ServiceAccount, in my use case I run things that need to use an [SA and an annotation ](https://www.eksworkshop.com/docs/security/iam-roles-for-service-accounts/add_irsa/) to reach certain resources in AWS.

PD: I've been using these charts for months and they've made my life a lot easier, I'm really appreciate the work :D

**Comment by laszlocph** [comment]
Did you try the `podAnnotations` field and `serviceAccount`?
