### ISSUE TITLE
Cert-Manager

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/onechart#22]
Hey thanks for your aweseome work! 

How about integrating cert-manager into the mix?

**Comment by laszlocph** [comment]
Hello, OneChart is made for apps that you develop and then deploy.

In this context your app is a Cert Manager user at most. When you define an ingress, you set a cert manager related annotation and that's it:

```diff
image:
  repository: my-app
  tag: 1.0.0

ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
+   cert-manager.io/cluster-issuer: letsencrypt
  host: my-app.mycompany.com
```

If you want to install Cert Manager (and manage amongst other infra tools) I recommend to check out https://github.com/gimlet-io/gimlet-stack

**Comment by appinteractive** [comment]
Hi @laszlocph, thanks for pointing that our but I honestly don't know how to use that stack. Is there any documentation how to start? I'm still diving into gimlet so maybe i'm not at the level needed yet 😬 and need some push into the right direction.

**Comment by laszlocph** [comment]
Gimlet Stack is work in progress, will be available in like 2 weeks, and then you can provision Cert Manager in your cluster.

Just wanted to say that installing Cert Manager is out of scope for OneChart, but using it is not more than adding a `cert-manager.io/cluster-issuer` as shown above.

I'm happy to help installing Cert Manager, just let me get Gimlet Stack to a point where it fits the larger picture.

In the meantime,
- you can install Cert Manager with the regular approach: https://cert-manager.io/docs/installation/kubernetes/
- or you can use the predecessor of Gimlet Stack, a service called 1clickinfra.com this video has a walkthrough about it: https://www.youtube.com/watch?v=B2B8EFYSH00&t=229s

**Comment by laszlocph** [comment]
You can also join Gimlet's Discord, I'm happy to clarify with screensharing if needed: https://discord.gg/ZwQDxPkYzE

**Comment by appinteractive** [comment]
Man @laszlocph Thanks for the input! I was trying to run cert-manager before but handeling multiple dependen charts is not that easy when you are not native to that. 

1Clickinfra is a treasure and I'm looking forward to test out the Gimlet-Stack! The only thing that was a missing peace for both, gimlet-stack and 1clickinfra was the best practice how to put your own charts into the system when not using gitops to the full. 

Other then that, I really like your work and am very gratefull that you are filling the gap!

**Comment by laszlocph** [comment]
@appinteractive you are so cool! Thank you for your words! Mean a lot :heart: 

> how to put your own charts into the system when not using gitops to the full.

One rudimentary way to reuse the automation 1clickinfra made for your own applications is described in 3 mins in this video:
https://www.youtube.com/watch?v=rlGJM19auJU&t=210s

The automated approach would be using GimletD from the Gimlet universe, but maybe just check this video and see how you can do it manually, and bump the version manually when you need to deploy something new.

**Comment by laszlocph** [comment]
I'm closing this issue as Gimlet Stack docs is released.

As for "how to put your own charts into the system when not using gitops to the full." maybe this helps:

https://gimlet.io/gimlet-stack/reusing-the-stack-repo-for-application-deployments/

**Comment by appinteractive** [comment]
Thanks! And forget the Part without gitops, I'm full in now. 😎
