### ISSUE TITLE
networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+

### ISSUE THREAD

**Issue by appinteractive** [gimlet-io/onechart#23]
Then using helm template onechart/onechart with ingress keys, I get follownig warning:

```
networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; 
use networking.k8s.io/v1 Ingress
```

**Comment by laszlocph** [comment]
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122

**Comment by laszlocph** [comment]
https://www.civo.com/learn/migrating-your-ingresses-in-k3s-1-20
https://kubernetes.io/blog/2021/07/26/update-with-ingress-nginx/

**Comment by laszlocph** [comment]
when this issue is done OneChart will only support cluster versions >= 1.19

**Comment by laszlocph** [comment]
TODO:
- [ ] check if the updated ingress spec works with ingress controllers pre v1 ingress support, aka Ingress Nginx 0.47

**Comment by laszlocph** [comment]
This is done now.

Next time we can consider compatibility conditionals like done here: https://github.com/grafana/helm-charts/blob/main/charts/grafana/templates/ingress.yaml#L2
