### ISSUE TITLE
Increase readiness probe's initial delay seconds maximum value

### ISSUE THREAD

**Issue by pavelkucera** [gimlet-io/onechart#33]
Hi,

Is it be possible to increase readiness probe's initial delay seconds maximum value from 60 seconds [0] to maybe 120 or 180 seconds?

I'm using onechart to run an app which simply doesn't start that fast.

[0] https://github.com/gimlet-io/onechart/blob/master/charts/onechart/values.schema.json#L391

**Comment by laszlocph** [comment]
tldr: We could increase it to 180 seconds.

- I believe the 60 seconds was picked based on what looks manageable on the UI when you configure the chart values with `gimlet chart configure`.
- Another consideration is what a modern cloud native app looks like, so from that perspective 180 may be too high.
- My last point is that perhaps the values are never validated against the schema in a normal helm templating process. So I would think you can set a higher value without getting a schema validation error.

**Comment by pavelkucera** [comment]
I have a setup where helm charts do get validated (gimlet/gimletd + flux) so I can't just ignore it :(.

I agree that 180 is too high for new apps, but it is a problem with an older one.
