### ISSUE TITLE
Allow additional arbitrary resources

### ISSUE THREAD

**Issue by LoicGombeaud** [gimlet-io/onechart#41]
Hello again!

The bitnami charts have a very useful `extraDeploy` value, that can be used to add any number of additional, arbitrary resources to a helm release. Would it be possible to have something similar here?

My use case: I need to add a Traefik `IngressRoute`, a Calico `NetworkPolicy`, and a `SealedSecret`.

Cheers,
Loïc

**Comment by laszlocph** [comment]
That is totally possible.

The Gimlet ecosystem has a similar feature already: the manifest is able to reference a Helm chart, perform a Kustomize patches on it, and append plain k8s manifests as well.

See examples here:
https://github.com/gimlet-io/gimlet/tree/main/examples/raw-manifest
Further examples and some mambling here:
https://book.gimlet.io/docs/developer-workflows/developer-workflows-with-gimlet/when-the-helm-abstraction-is-limiting

Do you use the Gimlet manfest? Is it a solution for you?

Adding an `extraDeploy` field in OneChart is also possible.

**Comment by LoicGombeaud** [comment]
Hi - sorry for the late reply.

I wish I could use the Gimlet ecosystem, but I'm still not using GitHub, so it's not an option at the moment, hence the request for an `extraDeploy` field directly in OneChart.

Cheers

**Comment by laszlocph** [comment]
Feature coming up!

**Comment by laszlocph** [comment]
Try this: https://github.com/gimlet-io/onechart/releases/tag/v0.36.0

Examples in this test: https://github.com/gimlet-io/onechart/blob/master/charts/onechart/tests/extraDeploy_test.yaml#L8

**Comment by LoicGombeaud** [comment]
Amazing, thanks!
