### ISSUE TITLE
Support host path volumes

### ISSUE THREAD

**Issue by lacarvalho91** [gimlet-io/onechart#47]
I use `onechart` a lot for setting up local integration test environments. Sometimes I need to mount test data from the host but it seems `onechart` doesn't allow that, unless I'm missing something.

**Comment by laszlocph** [comment]
You are right!

We can add hostpath, it is not a big thing, and a common usecase.

It will take a week or so due to things.. but I will be back.
In the meantime you can postprocess with Kustomize perhaps?

**Comment by laszlocph** [comment]
Fixed in https://github.com/gimlet-io/onechart/releases/tag/v0.39.0
