### ISSUE TITLE
Chart version v0.41.0 does not seem to have existingFileSecrets changes

### ISSUE THREAD

**Issue by whitedr** [gimlet-io/onechart#59]
Hi there.

I was trying to use the changes from https://github.com/gimlet-io/onechart/pull/53 which include support for referencing existing secrets and mounting them in the container filesystem.  This however is not working when I reference the v0.41.0 version of the chart (which is the latest) where this change was added.

If I look the released version diff I can see the changes here: https://github.com/gimlet-io/onechart/commit/afcfc36e5f4ce701012ec89b853de62afd6916f7#diff-bf919b6b281151a677d8090da5f1de872cca2fd7d56a7ec3935555a4e9d583e3

However if I download the chart tarball from here: https://chart.onechart.dev/onechart-0.41.0.tgz

and look at the file: `onechart/charts/common/templates/_volumesRef.yaml` I don't see the existingFileSecrets change.

So it looks like something's not quite right with that packaged version.  Am I missing something?

Thanks in advance!

**Comment by laszlocph** [comment]
You are absolutely right. We had some internal dependency shenanigans.
Fixed in https://github.com/gimlet-io/onechart/releases/tag/v0.42.0
