### ISSUE TITLE
Publish Onechart to an OCI registry

### ISSUE THREAD

**Issue by laszlocph** [gimlet-io/onechart#78]
https://helm.sh/docs/topics/registries/

The task is to modify Onechart's build and CI jobs to publish to an OCI registry. We would like to use the Github Package registry to host onechart.

Since you don't have access to our registry, publish it under your Github account and let us know what we need to replace when we merge.

Please provide a two liner on how to use it: `helm repo add, helm repo install`.

**Comment by spy-1234** [comment]
Hey, I would like to work on this issue.

**Comment by laszlocph** [comment]
Sure, go ahead.
Others may also submit pull requests to this one.
