### ISSUE TITLE
multiple ingress - paths

### ISSUE THREAD

**Issue by marinkobabic** [gimlet-io/onechart#88]
Multiple ingress paths for the same service are not supported

**Comment by laszlocph** [comment]
Have you seen the `ingresses` field?
https://github.com/gimlet-io/onechart/blob/master/charts/onechart/tests/ingress_domain_test.yaml#L93

Looking at the code, it may be supported. I never tried it, but you can try providing multiple ingresses under `ingresses` with a path specified per ingress.
