### ISSUE TITLE
Request for adding documentation - "Open Source Guidelines"

### ISSUE THREAD

**Issue by sourabhsingh282** [gimlet-io/onechart#9]
Hi Team

Can we add some general guidelines on this project about how to submit pull request and what are the contribution guidelines, if i want to file any bug/issue?

**Comment by laszlocph** [comment]
Definitely @sourabhsingh282 thank you for raising this!

**Comment by soniasingla** [comment]
@sourabhsingh282 if you run into any issues, feel free to ask in the comments! 🎉

**Comment by soniasingla** [comment]
Closing #10
